In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
import numpy as np
from pandas.io.parsers import read_csv

model = tf.global_variables_initializer()

data = read_csv('full_data_cut4.csv', sep=',')

xy = np.array(data,dtype=np.float32)

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
print(xy)

[[ 6.  4.  6.  7.]
 [ 8.  5.  8.  8.]
 [ 8.  6.  4.  8.]
 [10.  5.  5.  9.]
 [ 6.  5.  2.  7.]
 [ 8.  6.  3.  3.]
 [10.  5.  3.  8.]
 [ 6.  5.  7.  9.]
 [ 9.  5.  6.  8.]
 [ 8.  5.  4.  7.]
 [ 8.  5.  4.  8.]
 [ 7.  4.  5.  4.]
 [10.  4.  4.  8.]
 [ 8.  6.  2.  3.]
 [10.  5.  4.  7.]
 [ 8.  6.  2.  4.]
 [ 8.  5.  2.  7.]
 [ 7.  4.  4.  7.]
 [ 8.  5. 10.  8.]
 [ 7.  6.  5.  2.]
 [10.  4.  4.  7.]
 [10.  5. 10.  7.]
 [ 8.  5. 10. 10.]
 [10.  5.  8.  9.]
 [ 7.  4.  4.  6.]
 [ 9.  5.  8.  8.]
 [ 5.  5.  3.  2.]
 [10.  6.  3.  7.]
 [ 5.  5.  5.  3.]
 [ 6.  3.  4.  8.]
 [10.  3.  4.  8.]
 [ 6.  4.  3.  7.]
 [ 7.  5.  2.  8.]
 [10.  6.  7.  8.]
 [ 6.  5.  6. 10.]
 [ 7.  4.  2.  6.]
 [ 8.  5.  3.  7.]
 [10.  4.  3.  6.]
 [ 8.  6.  3.  8.]
 [ 7.  5.  2.  7.]
 [ 7.  5.  3.  7.]
 [10.  2.  2.  7.]
 [ 6.  4.  1.  8.]
 [ 6.  5.  5.  6.]
 [ 7.  4.  2.  5.]
 [ 6.  4.  8.  9.]
 [ 7.  5.  6. 10.]
 [ 7.  6.  2.  4.]
 [ 7.  6.  8.  7.]
 [ 5.  3.  3.  6.]
 [10.  3.  7.  7.]
 [ 8.  5.  3.  9.]
 [ 8.  6.  9

In [3]:
#다변인 선형회귀 : 모델에 영향을 미치는 변인이 여러 개 일 때 사용하는 모델
#즉 각각의 가중치가 변인에 곱해지는 형식으로 식을 세워야 함

In [4]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [5]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]),name="weight")
b = tf.Variable(tf.random_normal([1],5),name="bias")
#random_normal은 0과 1사이의 정규분포난수를 생성한다.

In [6]:
hypothesis = tf.matmul(X,W)+b
#tf.matmul은 3차원 이상의 행렬의 곱이다. 즉 X,W을 곱하라는 것이다.

In [7]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#reduce_mean은 시그마 기호(전체 원소 더한 값/원소 개수)

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.000005)
train = optimizer.minimize(cost)
#비용 최소화 코드 by경사하강법 이용

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(150001):
    cost_,hypo_,_,W_,b_ = sess.run([cost,hypothesis,train,W,b], feed_dict={X:x_data, Y:y_data})
    if step % 500 == 0:
        print("#",step,"손실 비용: ",cost_)
        print("-피로도: ",hypo_[0])    

# 0 손실 비용:  8.592175
-피로도:  [5.0693083]
# 500 손실 비용:  8.357837
-피로도:  [5.1021256]
# 1000 손실 비용:  8.135499
-피로도:  [5.141174]
# 1500 손실 비용:  7.923946
-피로도:  [5.183436]
# 2000 손실 비용:  7.722433
-피로도:  [5.227103]
# 2500 손실 비용:  7.5304155
-피로도:  [5.2711754]
# 3000 손실 비용:  7.347423
-피로도:  [5.315056]
# 3500 손실 비용:  7.1730204
-피로도:  [5.35841]
# 4000 손실 비용:  7.006806
-피로도:  [5.401041]
# 4500 손실 비용:  6.848433
-피로도:  [5.442995]
# 5000 손실 비용:  6.6975055
-피로도:  [5.48405]
# 5500 손실 비용:  6.553661
-피로도:  [5.524156]
# 6000 손실 비용:  6.416562
-피로도:  [5.563323]
# 6500 손실 비용:  6.285898
-피로도:  [5.601568]
# 7000 손실 비용:  6.1613626
-피로도:  [5.6389103]
# 7500 손실 비용:  6.0426702
-피로도:  [5.675368]
# 8000 손실 비용:  5.92955
-피로도:  [5.710968]
# 8500 손실 비용:  5.821735
-피로도:  [5.74572]
# 9000 손실 비용:  5.718979
-피로도:  [5.779649]
# 9500 손실 비용:  5.6210437
-피로도:  [5.8127728]
# 10000 손실 비용:  5.5277047
-피로도:  [5.845111]
# 10500 손실 비용:  5.4387445
-피로도:  [5.8766828]
# 11000 손실 비용:  5.3539577
-피로도:  [5.907505]
# 11500 손실 비용:  5.273149

# 93500 손실 비용:  3.6303554
-피로도:  [7.160844]
# 94000 손실 비용:  3.6303177
-피로도:  [7.161494]
# 94500 손실 비용:  3.6302814
-피로도:  [7.162115]
# 95000 손실 비용:  3.6302464
-피로도:  [7.162711]
# 95500 손실 비용:  3.630213
-피로도:  [7.1633]
# 96000 손실 비용:  3.6301816
-피로도:  [7.1638584]
# 96500 손실 비용:  3.6301496
-피로도:  [7.1644025]
# 97000 손실 비용:  3.6301208
-피로도:  [7.164939]
# 97500 손실 비용:  3.6300921
-피로도:  [7.165452]
# 98000 손실 비용:  3.6300645
-피로도:  [7.1659627]
# 98500 손실 비용:  3.6300383
-피로도:  [7.1664586]
# 99000 손실 비용:  3.6300125
-피로도:  [7.1669393]
# 99500 손실 비용:  3.6299891
-피로도:  [7.1674123]
# 100000 손실 비용:  3.6299653
-피로도:  [7.16788]
# 100500 손실 비용:  3.6299424
-피로도:  [7.168327]
# 101000 손실 비용:  3.629921
-피로도:  [7.168769]
# 101500 손실 비용:  3.6299
-피로도:  [7.169216]
# 102000 손실 비용:  3.6298795
-피로도:  [7.1696253]
# 102500 손실 비용:  3.62986
-피로도:  [7.170068]
# 103000 손실 비용:  3.6298409
-피로도:  [7.170494]
# 103500 손실 비용:  3.6298232
-피로도:  [7.1709156]
# 104000 손실 비용:  3.6298053
-피로도:  [7.1713214]
# 104500 손실 비용:  3.62978

In [11]:
print("가중치: ",W_)
print("편향: ",b_)

가중치:  [[ 0.23708485]
 [-0.37105516]
 [ 0.24200976]]
편향:  [5.7965007]


In [12]:
saver = tf.train.Saver()
#모든 변수들 저장
save_path = saver.save(sess,"./saved.cpkt")
#경로 지정
print("학습된 모델을 저장했습니다.")

학습된 모델을 저장했습니다.
