In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 
import numpy as np
from pandas.io.parsers import read_csv

model = tf.global_variables_initializer()

data = read_csv('correct_data.csv', sep=',')

xy = np.array(data,dtype=np.float32)

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
print(xy)

[[ 4.  6.  7.]
 [ 5.  8.  8.]
 [ 6.  4. 10.]
 [ 5.  5.  9.]
 [ 5.  2.  7.]
 [ 5. 10. 10.]
 [ 6. 10. 10.]
 [ 7. 10. 10.]
 [ 6.  3.  3.]
 [ 5.  9.  9.]
 [ 3. 10. 10.]
 [ 4. 10. 10.]
 [ 3. 10. 10.]
 [ 4. 10. 10.]
 [ 7. 10. 10.]
 [ 6. 10. 10.]
 [ 5.  3. 10.]
 [ 5.  7.  9.]
 [ 5.  6.  8.]
 [ 5.  4.  7.]
 [ 5.  4.  8.]
 [ 4.  5.  4.]
 [ 4.  4.  8.]
 [ 6.  2.  3.]
 [ 5.  4.  7.]
 [ 6.  2.  4.]
 [ 5.  2.  7.]
 [ 4.  4.  7.]
 [ 5. 10.  8.]
 [ 6.  5.  2.]
 [ 4.  4.  7.]
 [ 5. 10.  7.]
 [ 5. 10. 10.]
 [ 5.  8.  9.]
 [ 4.  4.  6.]
 [ 5.  8.  8.]
 [ 5.  3.  2.]
 [ 6.  3.  7.]
 [ 5.  5.  3.]
 [ 3.  4.  8.]
 [ 3.  4.  8.]
 [ 4.  3.  7.]
 [ 5.  2.  8.]
 [ 6.  7. 10.]
 [ 5.  6. 10.]
 [ 4.  2.  6.]
 [ 5.  3.  7.]
 [ 4.  3.  6.]
 [ 6.  3.  8.]
 [ 5.  2.  7.]
 [ 5.  3.  7.]
 [ 2.  2.  7.]
 [ 4.  1.  8.]
 [ 5.  5.  6.]
 [ 4.  2.  5.]
 [ 4.  8.  9.]
 [ 5.  6. 10.]
 [ 6.  2.  4.]
 [ 6.  8.  7.]
 [ 3.  3.  6.]
 [ 3.  7.  7.]
 [ 5.  3.  9.]
 [ 6.  9.  9.]
 [ 6.  2.  6.]
 [ 7.  4.  8.]
 [ 4.  8.  2.]
 [ 5.  4. 

In [3]:
#다변인 선형회귀 : 모델에 영향을 미치는 변인이 여러 개 일 때 사용하는 모델
#즉 각각의 가중치가 변인에 곱해지는 형식으로 식을 세워야 함

In [4]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [5]:
X = tf.placeholder(tf.float32,shape=[None,2])
Y = tf.placeholder(tf.float32,shape=[None,1])
W = tf.Variable(tf.random_normal([2,1]),name="weight")
b = tf.Variable(tf.random_normal([1]),name="bias")
#random_normal은 0과 1사이의 정규분포난수를 생성한다.

In [6]:
hypothesis = tf.matmul(X,W)+b
#tf.matmul은 3차원 이상의 행렬의 곱이다. 즉 X,W을 곱하라는 것이다.

In [7]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
#reduce_mean은 시그마 기호(전체 원소 더한 값/원소 개수)

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.000005)
train = optimizer.minimize(cost)
#비용 최소화 코드 by경사하강법 이용

In [9]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(100001):
    cost_,hypo_,_,W_,b_ = sess.run([cost,hypothesis,train,W,b], feed_dict={X:x_data, Y:y_data})
    if step % 500 == 0:
        print("#",step,"손실 비용: ",cost_)
        print("-피로도: ",hypo_[0])    

# 0 손실 비용:  113.190765
-피로도:  [-4.1734457]
# 500 손실 비용:  70.00065
-피로도:  [-1.792918]
# 1000 손실 비용:  44.76247
-피로도:  [0.02855587]
# 1500 손실 비용:  29.990883
-피로도:  [1.4231254]
# 2000 손실 비용:  21.322798
-피로도:  [2.491678]
# 2500 손실 비용:  16.21494
-피로도:  [3.3112402]
# 3000 손실 비용:  13.1847515
-피로도:  [3.940627]
# 3500 손실 비용:  11.368008
-피로도:  [4.424734]
# 4000 손실 비용:  10.260854
-피로도:  [4.797837]
# 4500 손실 비용:  9.569468
-피로도:  [5.086122]
# 5000 손실 비용:  9.122516
-피로도:  [5.309569]
# 5500 손실 비용:  8.820028
-피로도:  [5.4834366]
# 6000 손실 비용:  8.603643
-피로도:  [5.619383]
# 6500 손실 비용:  8.439259
-피로도:  [5.726304]
# 7000 손실 비용:  8.306914
-피로도:  [5.810993]
# 7500 손실 비용:  8.194898
-피로도:  [5.878639]
# 8000 손실 비용:  8.096303
-피로도:  [5.9332066]
# 8500 손실 비용:  8.00704
-피로도:  [5.9777236]
# 9000 손실 비용:  7.9246454
-피로도:  [6.014497]
# 9500 손실 비용:  7.847629
-피로도:  [6.045302]
# 10000 손실 비용:  7.775059
-피로도:  [6.071495]
# 10500 손실 비용:  7.7063117
-피로도:  [6.0940843]
# 11000 손실 비용:  7.6410136
-피로도:  [6.1139007]
# 11500 손실 비용

# 94000 손실 비용:  6.166913
-피로도:  [6.650444]
# 94500 손실 비용:  6.166086
-피로도:  [6.6508613]
# 95000 손실 비용:  6.1652613
-피로도:  [6.6512785]
# 95500 손실 비용:  6.1644373
-피로도:  [6.6516957]
# 96000 손실 비용:  6.163613
-피로도:  [6.652113]
# 96500 손실 비용:  6.1627903
-피로도:  [6.652539]
# 97000 손실 비용:  6.161973
-피로도:  [6.653075]
# 97500 손실 비용:  6.1611567
-피로도:  [6.653574]
# 98000 손실 비용:  6.1603413
-피로도:  [6.6539316]
# 98500 손실 비용:  6.159526
-피로도:  [6.6542892]
# 99000 손실 비용:  6.1587124
-피로도:  [6.654647]
# 99500 손실 비용:  6.157898
-피로도:  [6.6550045]
# 100000 손실 비용:  6.1570854
-피로도:  [6.655362]


In [11]:
print("가중치: ",W_)
print("편차: ",b_)

가중치:  [[0.98142856]
 [0.5654063 ]]
편차:  [-0.6627896]


In [37]:
saver = tf.train.Saver()
#모든 변수들 저장
save_path = saver.save(sess,"./saved.cpkt")
#경로 지정
print("학습된 모델을 저장했습니다.")

학습된 모델을 저장했습니다.
